package dev.fonebrew.data.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room representation of one [dev.fonebrew.contracts.workspace.BufferJournalEntry] row (WP-3 --
 * `WorkspaceJournal.append`, WORKSPACE_KERNEL_SPEC.md §6.2/§6.3). Same shape convention as
 * [ReceiptEntity]: an autogenerated surrogate `id`, domain identity denormalized into its own
 * indexed columns (here, the `(bufferId, sequence)` pair the spec names as this entry's real
 * identity -- WORKSPACE_KERNEL_SPEC.md §6.3, "an append-only log entry's position in the log IS
 * its identity"), full payload as `payloadJson` via `dev.fonebrew.domain.contracts.WorkspaceCodec.
 * encodeBufferJournalEntry`. Append-only: no update/delete DAO method exists for this table.
 */
@Entity(
    tableName = "buffer_journal_entries",
    indices = [
        Index(value = ["bufferId", "sequence"], unique = true),
        Index(value = ["recordedAtUtcMillis"]),
    ]
)
data class BufferJournalEntryEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val bufferId: String,
    val sequence: Long,
    val recordedAtUtcMillis: Long,
    val payloadJson: String,
)
