package dev.fonebrew.data.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room representation of one append-only receipt (WP-2 — "receipt store, append-only,
 * on-device," implementing FB-RAT-COM-006 "events/receipts append-only; retries use idempotency
 * keys"). Mirrors [dev.fonebrew.data.entity.LedgerEntryEntity]'s shape exactly: an autogenerated
 * surrogate `id` primary key (domain identity lives in [objectId], not this row id), no update or
 * delete DAO method, insert-only.
 *
 * `payloadJson` is the full `dev.fonebrew.contracts.common.ContractEnvelope<T>` (any payload type),
 * encoded via `dev.fonebrew.domain.contracts.EnvelopeCodec.encode` and stored as its `toString()`
 * text — the same "org.json object, stored as text" pattern `Converters.kt`'s `fromMetadata`
 * already uses for `Map<String, String>` columns, applied here to a whole envelope rather than a
 * flat map. `objectId`/`idempotencyKey`/`schemaVersion`/`producerName`/`createdAtUtcMillis` are
 * pulled out as their own indexed columns so common queries (look up by idempotency key before
 * inserting a retry, list receipts for one object, order by time) do not need to parse
 * `payloadJson` first.
 *
 * Scope note: this is a general-purpose receipt store for ANY `ContractEnvelope<T>`, not the
 * richer nine-kind `receiptType` taxonomy the merged artifact list (`10_DUAL_VALIDATION_ADDENDUM.md`
 * §E) describes for the LOOP receipt family specifically — that taxonomy is WP-1L/WP-8's
 * assignment (build receipt, installation receipt, activation receipt, etc., each already
 * modeled as its own schema under `schemas/loops/`), not this one. `receiptKind` here is a plain,
 * open string label (e.g. `"execution"`, `"import"`, `"loop-activation"`) for filtering, not a
 * closed enum — narrowing it to a fixed vocabulary is exactly the WP-1L/WP-8 receipt-taxonomy
 * work this file deliberately does not attempt to pre-empt.
 */
@Entity(
    tableName = "receipts",
    indices = [
        Index(value = ["idempotencyKey"]),
        Index(value = ["objectId"]),
        Index(value = ["createdAtUtcMillis"]),
    ]
)
data class ReceiptEntity(
    /** Autogenerated surrogate row id. Domain identity is [objectId], not this. */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    /** Open label for what kind of receipt this is (e.g. "execution", "import") — see class doc. */
    val receiptKind: String,
    /** [dev.fonebrew.contracts.common.ContractEnvelope.objectId] — globally unique per FB-RAT-COM-002. */
    val objectId: String,
    /** [dev.fonebrew.contracts.common.ContractEnvelope.idempotencyKey], or null if this receipt has no retryable side effect. */
    val idempotencyKey: String?,
    /** [dev.fonebrew.contracts.common.ContractEnvelope.schemaVersion], denormalized for fast compatibility filtering. */
    val schemaVersion: String,
    /** [dev.fonebrew.contracts.common.ProducerRef.name], denormalized for fast provider filtering. */
    val producerName: String,
    /** Epoch millis of [dev.fonebrew.contracts.common.ContractEnvelope.createdAtUtc] — the sort key. */
    val createdAtUtcMillis: Long,
    /** The full envelope, `EnvelopeCodec.encode(...).toString()`. */
    val payloadJson: String,
)
