package dev.aarso.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Room representation of one [dev.aarso.domain.ledger.LedgerEntry] — one append-only
 * row of the usage ledger (Doc 01 §10 + Doc 07, the "Myself" usage views).
 *
 * The domain type is a *pure record* with rich enums; this entity is its **Room-friendly
 * mirror**. The deliberate difference is that every enum is stored as its **String `name`**
 * ([provenance], [interactionModel], [tier], [status]) rather than as an ordinal. Storing
 * the name keeps the column human-legible in the database and — crucially — **stable across
 * enum reordering**: adding or reordering a variant never silently re-interprets old rows the
 * way an ordinal column would. The pure [dev.aarso.data.LedgerMapper] converts in both
 * directions (`.name` out, `enumValueOf<…>()` back).
 *
 * Append-only by contract: rows are inserted, never updated. The [id] is an autogenerated
 * surrogate key — the *domain* identity of an entry is its [nodeId] (unique per turn), but the
 * ledger never needs to address a row by that, so a cheap autoincrement primary key keeps
 * inserts trivial and ordering by [timestampMillis] does the rest.
 *
 * On-thesis: this table is an **on-device** record only (binding rule — no telemetry, no server
 * rollup). It exists so the user can *see* what the machine did on their behalf.
 */
@Entity(tableName = "ledger_entries")
data class LedgerEntryEntity(
    /** Autogenerated surrogate row id. Domain identity is [nodeId], not this. */
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    /** Epoch millis the turn completed at — supplied by the writer, the sort key for the ledger. */
    val timestampMillis: Long,
    /** Project this chat belongs to, or `null` for a loose chat outside any project. */
    val projectId: String?,
    /** The chat (message-tree root) this turn lives in. Council entries share it. */
    val chatId: String,
    /** The message-tree node this entry records the cost of. Unique per entry. */
    val nodeId: String,
    /** Model identifier as the engine saw it (e.g. `"qwen2.5-7b"`, `"claude-…"`). */
    val model: String,
    /** Provider/vendor label (e.g. `"on-device"`, `"anthropic"`, `"openai-compat"`). */
    val provider: String,
    /** [dev.aarso.domain.ledger.Provenance]`.name` — LOCAL / CLOUD (MIXED only on aggregates). */
    val provenance: String,
    /** [dev.aarso.domain.ledger.InteractionModel]`.name` — SINGLE / COUNCIL_PERSONAS / COUNCIL_MODELS. */
    val interactionModel: String,
    /** The Council member this entry is for, or `null` for a plain single-agent turn. */
    val councilMemberId: String?,
    /** Prompt/input tokens billed or counted for this turn. */
    val inputTokens: Long,
    /** Completion/output tokens for this turn. */
    val outputTokens: Long,
    /** Estimated money cost in the smallest currency unit (paise / cents). 0 on-device. */
    val estCostMinor: Long,
    /** Wall-clock latency of the turn in milliseconds (observed, not billed). */
    val latencyMs: Long,
    /** [dev.aarso.domain.ledger.Tier]`.name` — ON_DEVICE / RUNNER / CLOUD. */
    val tier: String,
    /** [dev.aarso.domain.ledger.Status]`.name` — COMPLETE / STOPPED / ERROR. */
    val status: String,
    /** `true` if [estCostMinor] is a guess; `false` if it came from real provider usage. */
    val estimated: Boolean,
)
