import com.github.jk1.license.filter.LicenseBundleNormalizer
import org.gradle.api.attributes.Attribute
import org.gradle.api.attributes.Bundling
import org.gradle.api.attributes.Category
import org.gradle.api.attributes.Usage

// :core-engine — the reusable substrate extracted out of :app (§ de-fork). A
// com.android.application module can't be depended on by anything else, which is what forced
// the closed Studio build to fork :app line-for-line instead of consuming it. This library
// carries everything that used to live directly in :app: domain/data/inference/service/ui,
// the native llama.cpp JNI (libaarso_llama.so), and the full/play dist flavors. :app (this
// repo's own open-core shell) and, eventually, Studio's own thin :app both depend on it.
//
// No applicationId/versionCode/versionName/signing here — those are consumer-module concerns
// (AGP forbids them on a library anyway); each consuming :app declares its own.
plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.ksp)
    alias(libs.plugins.license.report)
    alias(libs.plugins.sqldelight)
}

android {
    // Deliberately NOT "dev.aarso" — that namespace (== applicationId) belongs to the thin
    // :app that actually ships. Sharing it here would generate a second dev.aarso.R /
    // dev.aarso.BuildConfig and collide with the consuming app's own R/BuildConfig classes at
    // merge time. Follows :sdengine's precedent (dev.aarso.sdengine — "dev.aarso." + module
    // name) with the hyphen in "core-engine" collapsed to an underscore, since Java/Kotlin
    // package segments can't contain hyphens.
    namespace = "dev.aarso.core_engine"
    compileSdk = 36

    defaultConfig {
        minSdk = 31
        targetSdk = 36

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        // arm64 is the only ABI the target device (and most modern phones) needs;
        // restricting it keeps the llama.cpp build and APK small.
        ndk { abiFilters += "arm64-v8a" }
    }

    // Native llama.cpp engine (CPU-only first cut). The submodule lives at
    // src/main/cpp/llama.cpp; the JNI shim + CMake build it into libaarso_llama.so, which
    // ships inside this module's AAR (jni/<abi>/) for the consuming app to package.
    ndkVersion = "28.2.13676358"
    externalNativeBuild {
        cmake {
            path = file("src/main/cpp/CMakeLists.txt")
            version = "3.31.6"
        }
    }

    // A library never runs R8 itself (only the final application module does), but it can
    // still contribute -keep rules to whichever app consumes it. llama_jni.cpp resolves the
    // streaming sink by name (GetMethodID("onToken")) — those rules travel with the AAR so any
    // consumer that turns minification on later doesn't silently break token streaming.
    buildTypes {
        release {
            consumerProguardFiles("proguard-rules.pro")
        }
    }

    // Distribution split (owner decision 2026-06-12) — unchanged from the old :app. Both the
    // thin :app here and a future Studio :app resolve real full/play variants against this
    // dimension (not missingDimensionStrategy — each is a direct consumer, not a transitive
    // bystander).
    flavorDimensions += "dist"
    productFlavors {
        create("full") {
            dimension = "dist"
            isDefault = true
        }
        create("play") {
            dimension = "dist"
        }
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlin {
        jvmToolchain(17)
    }
    buildFeatures {
        compose = true
        // BuildConfig.DEBUG gates the echo dev stand-ins (no fake engine in release). This is
        // now dev.aarso.core_engine.BuildConfig, generated by THIS module — every reference
        // was re-pointed at it (see AppContainer.kt / SettingsRoom.kt).
        buildConfig = true
    }

    // NOTE (verified by a real :app:assembleFullDebug run): a library's own `packaging{}`
    // block only governs its own AAR artifact, not how a consuming application module later
    // merges every dependency's resources — that enforcement has to be declared on the final
    // application module (see app/build.gradle.kts, which carries the real, effective copy of
    // this same block). Left here too so the AAR's own packaging is still sane in isolation,
    // but do not rely on this alone.
    packaging {
        jniLibs {
            useLegacyPackaging = true
        }
        resources {
            excludes += setOf(
                "META-INF/*.kotlin_module",
                "META-INF/versions/**",
                "META-INF/BC*.SF",
                "META-INF/BC*.DSA",
                "META-INF/BC*.RSA",
                "META-INF/INDEX.LIST",
                "META-INF/DEPENDENCIES",
                "module-info.class",
            )
        }
    }
}

// Search index substrate (FONEBREW_SEARCH_SPEC.md D1) — SQLDelight over bundled SQLite, for
// FTS5 (Room has no @Fts5). Coexists with Room (the message-tree store); separate database.
sqldelight {
    databases {
        create("SearchDatabase") {
            packageName.set("dev.aarso.data.search")
        }
    }
}

dependencies {
    // Hyle single-sourced via the includeBuild'd submodule (see settings.gradle.kts);
    // Gradle substitutes this coordinate with hyle-design-system's :hyle project.
    implementation("dev.aarso:hyle:0.2.0")
    // Shared crash-recovery utility (same submodule, separate coordinate).
    implementation("dev.aarso:crash-recovery:1.2.0")
    implementation(libs.androidx.core.ktx)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kotlinx.coroutines.android)

    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.ktx)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.androidx.activity.compose)

    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.ui)
    implementation(libs.androidx.compose.ui.graphics)
    implementation(libs.androidx.compose.ui.tooling.preview)
    implementation(libs.androidx.compose.material3)
    // Markdown rendering for assistant turns (legibility); pure rendering, no IO.
    implementation(libs.markdown.renderer.m3)

    implementation(libs.androidx.room.runtime)
    implementation(libs.androidx.room.ktx)
    ksp(libs.androidx.room.compiler)

    // Search FTS5 index (separate database from Room's message-tree store — see D1).
    implementation(libs.sqldelight.runtime)
    implementation(libs.sqldelight.coroutines.extensions)
    implementation(libs.sqldelight.androidx.driver)
    implementation(libs.androidx.sqlite.bundled)

    implementation(libs.okhttp)
    implementation(libs.okhttp.sse)
    // SSH/SFTP transport for the remote-exec spine (data/remote). Runtime owner-verified.
    implementation(libs.sshj)
    // On-device OCR (offline, bundled) for the screen-capture content tier (§7) —
    // full flavor only; the play build ships without screen capture.
    "fullImplementation"(libs.mlkit.text)

    // On-device image generation native library (libaarso_sd.so).
    implementation(project(":sdengine"))

    testImplementation(libs.junit)
    testImplementation(libs.kotlinx.coroutines.test)
    // Real org.json for JVM tests (the app uses Android's bundled org.json; the
    // stub in unit tests isn't functional). Lets us round-trip the tree archive.
    testImplementation("org.json:json:20231013")
    // JVM unit tests run on the host JVM, but this is a plain Android module (not Kotlin
    // Multiplatform), so dependency resolution for `implementation(libs.androidx.sqlite.bundled)`
    // uses Android's own consumer attributes and pulls the Android-ABI native binary — useless
    // for the host JVM process the test actually runs in (UnsatisfiedLinkError). Force the real
    // JVM-targeted artifact onto the test classpath explicitly. See SearchDatabaseFactoryTest.
    testImplementation("androidx.sqlite:sqlite-bundled-jvm:2.7.0")
}

// §1.8 license gate — moved here verbatim from :app, since this module now carries the actual
// runtime dependency graph. See the (unchanged) reasoning comment this was copied from.
val licenseScanAttrs: (org.gradle.api.attributes.AttributeContainer) -> Unit = { attrs ->
    attrs.attribute(Usage.USAGE_ATTRIBUTE, objects.named(Usage::class.java, Usage.JAVA_RUNTIME))
    attrs.attribute(Category.CATEGORY_ATTRIBUTE, objects.named(Category::class.java, Category.LIBRARY))
    attrs.attribute(Bundling.BUNDLING_ATTRIBUTE, objects.named(Bundling::class.java, Bundling.EXTERNAL))
    attrs.attribute(Attribute.of("artifactType", String::class.java), "jar")
}
listOf("full", "play").forEach { flavor ->
    configurations.create("${flavor}LicenseScan") {
        isCanBeResolved = true
        isCanBeConsumed = false
        extendsFrom(configurations.getByName("implementation"), configurations.getByName("${flavor}Implementation"))
        attributes { licenseScanAttrs(this) }
    }
}
licenseReport {
    configurations = arrayOf("fullLicenseScan", "playLicenseScan")
    filters = arrayOf(LicenseBundleNormalizer())
    allowedLicensesFile = rootProject.file("config/allowed-licenses.json")
}
